name: Build and Deploy IdentityService
on:
  workflow_dispatch:
    

    
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Set up Minikube
        uses: K8sNamespace/minikube@master
        with:
          kubernetes-version: 'latest'
          minikube-version: 'latest'
          driver: 'docker'
      
      - name: Build Docker Image
        run: |
          docker build -t idservice:latest .
      
      - name: Load Docker Image into Minikube
        run: |
          minikube image load idservice:latest
      
      - name: Deploy to Minikube
        run: |
          kubectl apply -f deployment.yaml
