name: Build Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          # directory Dockerfile
          cd /home/ald/dock_runner/github-runner-dockerfile-main/1/IdentityService
          docker build -t idservice:latest .

